steps:
  - label: ":anka: TESTING"
    command: |
      env
      whoami
      hostname
      pwd
      ls -la
    # agents:
    #   queue: mac-anka
    plugins:
      - veertuinc/anka#v2.0.0:
          vm-name: 26.3-arm64
          # copy-in-host-path: /tmp/buildkite-cache/${BUILDKITE_AGENT_ID}
          # copy-in-vm-path: /tmp/buildkite-cache
          copy-out-vm-path: /tmp/buildkite-cache
          copy-out-host-path: /tmp/buildkite-cache/${BUILDKITE_AGENT_ID}
