#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck disable=SC1090,SC1091
. "$DIR/../lib/shared.bash"

job_image_name="$(plugin_read_config VM_NAME)-${BUILDKITE_JOB_ID}"

echo "--- :anka: Cloning $(plugin_read_config VM_NAME) to $job_image_name"
# shellcheck disable=SC2086,SC2154
plugin_prompt_and_run anka $ANKA_DEBUG clone "$(plugin_read_config VM_NAME)" "$job_image_name"

#####################################
# Handle modifications to CPU/RAM/etc
BUILDKITE_PLUGIN_ANKA_MODIFY_CPU=$(plugin_read_list MODIFY_CPU)
BUILDKITE_PLUGIN_ANKA_MODIFY_RAM=$(plugin_read_list MODIFY_RAM)
BUILDKITE_PLUGIN_ANKA_MODIFY_MAC=$(plugin_read_list MODIFY_MAC)

if [[ -n "${BUILDKITE_PLUGIN_ANKA_MODIFY_CPU}" ]] || [[ -n "${BUILDKITE_PLUGIN_ANKA_MODIFY_RAM}" ]] || [[ -n "${BUILDKITE_PLUGIN_ANKA_MODIFY_MAC}" ]]; then
  echo "--- :anka: Ensuring $job_image_name is stopped"
  FORCED=${FORCED:-false} # Used for bats triggering of ops
  stop_ops=()
  # shellcheck disable=SC2086
  ( $FORCED || anka list "$job_image_name" 2>/dev/null | grep -q "suspended" ) && stop_ops+=("--force")
  # shellcheck disable=SC2086
  plugin_prompt_and_run anka stop "${stop_ops[@]:+${stop_ops[@]}}" "$job_image_name"
fi

acceptable_pattern='^[0-9]+$'
if [[ -n "${BUILDKITE_PLUGIN_ANKA_MODIFY_CPU}" ]]; then
  [[ ! "$BUILDKITE_PLUGIN_ANKA_MODIFY_CPU" =~ $acceptable_pattern ]] && echo "Acceptable input: [0-9]+" && exit 1
  echo "--- :anka: Modifying CPU cores to ${BUILDKITE_PLUGIN_ANKA_MODIFY_CPU}"
  # shellcheck disable=SC2086
  plugin_prompt_and_run anka modify $job_image_name set cpu $BUILDKITE_PLUGIN_ANKA_MODIFY_CPU
fi

if [[ -n "${BUILDKITE_PLUGIN_ANKA_MODIFY_RAM}" ]]; then
  [[ ! "$BUILDKITE_PLUGIN_ANKA_MODIFY_RAM" =~ $acceptable_pattern ]] && echo "Acceptable input: [0-9]+" && exit 1
  echo "--- :anka: Modifying RAM to ${BUILDKITE_PLUGIN_ANKA_MODIFY_RAM}G"
  # shellcheck disable=SC2086
  plugin_prompt_and_run anka modify $job_image_name set ram ${BUILDKITE_PLUGIN_ANKA_MODIFY_RAM}G
fi

acceptable_mac_pattern='^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$'
if [[ -n "${BUILDKITE_PLUGIN_ANKA_MODIFY_MAC}" ]]; then
  [[ ! "$BUILDKITE_PLUGIN_ANKA_MODIFY_MAC" =~ $acceptable_mac_pattern ]] && echo "Acceptable input: $acceptable_mac_pattern" && exit 1
  echo "--- :anka: Modifying MAC to ${BUILDKITE_PLUGIN_ANKA_MODIFY_MAC}"
  # shellcheck disable=SC2086
  plugin_prompt_and_run anka modify $job_image_name set network-card --mac ${BUILDKITE_PLUGIN_ANKA_MODIFY_MAC}
fi