#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck disable=SC1090,SC1091
. "$DIR/../lib/shared.bash"

# cleanup_job_vm reads global job_image_name (see lib/shared.bash).
# shellcheck disable=SC2034
job_image_name="$(plugin_read_config VM_NAME)-$BUILDKITE_JOB_ID"

cleanup_job_vm
